### ISSUE TITLE
receive links

### ISSUE THREAD

**Issue by Magenda** [scottrules44/firebaseDynamicLinks-demo#1]
Does this plugin support receiving dynamic links as described in firebase documentation? Where can i find the supported functions? 

Thanks

**Comment by scottrules44** [comment]
Yes you can see in the sample
`
Runtime:addEventListener("firebaseDynamicLinks", function(e)
  print(json.encode(e))
end)`

Look under Runtime Events in docs https://scotth.tech/plugin-firebaseDynamicLinks
